version: '2.1'
services:
  demo-elisa-broker:
    image: rmohr/activemq:5.14.3-alpine
    restart: always
    ports:
      - "61616:61616"
      - "8161:8161"
  demo-elisa-sender:
    build: ./demo-elisa-sender/.
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mraab
      - MYSQL_USER=mraab
      - MYSQL_PASSWORD=mraab
      - MYSQL_DATABASE=mraab