server:
  port: 8084

elisa:
    broker-url: tcp://localhost:61616
    destination-name: elisa-mailbox
wms:
    broker-url: tcp://localhost:61617
    destination-name: wms-mailbox

spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/mraab
    username: mraab
    password: mraab
    continue-on-error: true

